#' Preprocess numeric data for DataSHIELD box plots
#'
#' Calls the server-side preprocessing function
#' \code{boxPlotGG_data_Treatment_numericDS} for a numeric vector and assigns
#' the result on each DataSHIELD server as \code{boxPlotRawDataNumeric}.
#'
#' @param vector Character string specifying the server-side numeric vector to
#'   preprocess, for example \code{"pooled$weight_T0"}.
#' @param datasources DataSHIELD connections object. Default is
#'   \code{datashield.connections_find()}.
#'
#' @return Invisibly returns the result of \code{DSI::datashield.assign.expr}.
#'   The main effect is assignment of \code{boxPlotRawDataNumeric} on each
#'   server.
#'
#' @examples
#' if (require(DSLite)) {
#' data('CNSIM1')
#' data('CNSIM2')
#'
#' # build a DSLite server with the datasets inside
#' dslite.server1 <- DSLite::newDSLiteServer(tables=list(table1=CNSIM1))
#' dslite.server2 <- DSLite::newDSLiteServer(tables=list(table2=CNSIM2))
#'
#' # build DS login information
#' builder <- DSI::newDSLoginBuilder()
#' builder$append(server = 'server1', driver = 'DSLiteDriver', url = 'dslite.server1')
#' builder$append(server = 'server2', driver = 'DSLiteDriver', url = 'dslite.server2')
#' logindata <- builder$build()
#'
#' # do login and table assignment
#' cur_conn <- DSI::datashield.login(logindata)
#' datashield.assign.table(cur_conn, 'pooled', table = list(server1='table1', server2='table2'))
#'
#' preprocessBoxPlot("pooled$PM_BMI_CONTINUOUS", datasources = cur_conn)
#' cally <- "boxPlotGGDS(boxPlotRawDataNumeric, NULL, NULL)"
#' DSI::datashield.aggregate(cur_conn, as.symbol(cally))
#'
#' preprocessBoxPlot("pooled$LAB_TSC", datasources = cur_conn)
#' cally <- "boxPlotGGDS(boxPlotRawDataNumeric, pooled$GENDER, pooled$PM_BMI_CATEGORICAL)"
#' srv_res <- DSI::datashield.aggregate(cur_conn, as.symbol(cally))
#' }
#'
#' @export
#' @importFrom DSI datashield.assign.expr
preprocessBoxPlot <- function(vector, datasources = datashield.connections_find()) {
  cally <- paste0("boxPlotGG_data_Treatment_numericDS(", vector, ")")
  DSI::datashield.assign.expr(datasources, "boxPlotRawDataNumeric", as.symbol(cally))
}

#' Pool DataSHIELD box plot results across servers
#'
#' Pools server-side box plot summaries returned by \code{boxPlotGGDS}. The
#' function combines per-server summary data and computes weighted averages of
#' the box plot statistics using the server-side cell counts as weights.
#'
#' @param srv_res A non-empty list. Each element should be the server-side result
#'   of \code{boxPlotGGDS} and should contain a \code{data} element. The
#'   \code{data} element should contain \code{ymin}, \code{lower},
#'   \code{middle}, \code{upper}, \code{ymax}, and \code{n}. Optional grouping
#'   columns are \code{group}, \code{group2}, and \code{x}.
#'
#' @return A \code{data.table} containing pooled box plot statistics:
#' \describe{
#'   \item{ymin}{Weighted pooled lower whisker.}
#'   \item{lower}{Weighted pooled lower hinge.}
#'   \item{middle}{Weighted pooled median.}
#'   \item{upper}{Weighted pooled upper hinge.}
#'   \item{ymax}{Weighted pooled upper whisker.}
#' }
#' Grouping columns such as \code{group}, \code{group2}, and \code{x} are
#' retained when present.
#'
#' @examples
#' srv_res <- list(
#'   server1 = list(data = data.frame(
#'     x = "v1", ymin = 1, lower = 2, middle = 3,
#'     upper = 4, ymax = 5, n = 100
#'   )),
#'   server2 = list(data = data.frame(
#'     x = "v1", ymin = 2, lower = 3, middle = 4,
#'     upper = 5, ymax = 6, n = 150
#'   ))
#' )
#'
#' poolBoxPlot(srv_res)
#'
#' @export
#' @importFrom data.table data.table
poolBoxPlot <- function(srv_res) {

  # reduce to $data and addserver column
  dfs <- lapply(names(srv_res), function(srv) {
    df <- srv_res[[srv]]$data
    if (is.null(df)) return(NULL)
    df$server <- srv
    df
  })

  # combine data.frames
  combined <- do.call(rbind, dfs)

  if ("x" %in% names(combined)) {
    names(combined)[names(combined) == "x"] <- "variable"
  }
  group_vars <- intersect(c("variable", "group", "group2"), names(combined))
  #group_vars <- intersect(c("group","group2","x"), names(combined))  # why did I introduce group x??? or is this for requesting multiple variables? then adapt the documentation, which is misleading on that.

  combined <- data.table::data.table(combined)

  out <- dsBaseClient:::computeWeightedMeans(combined,
                       variables = c("ymin", "lower", "middle", "upper", "ymax"),
                       weight = "n",
                       by = group_vars)

  class(out) <- c("dsPooledBoxPlot", class(out))
  out
}

#' Plot pooled DataSHIELD box plot results
#'
#' Creates a \pkg{ggplot2} box plot from pooled box plot statistics generated by
#' \code{poolBoxPlot}. The x-axis represents the server-side variable names for
#' which box plots were computed. Optional \code{group} and \code{group2}
#' columns are used for fill grouping and faceting, respectively.
#'
#' @param data An object of class \code{PooledBoxPlot} (which is a data frame
#'   or \code{data.table}) containing pooled box plot statistics as returned by
#'   \code{poolBoxPlot}. Required columns are \code{x}, \code{ymin}, \code{lower},
#'   \code{middle}, \code{upper}, and \code{ymax}. Optional columns are
#'   \code{group} and \code{group2}.
#' @param xlabel Character string for the x-axis label. Default is
#'   \code{NULL}.
#' @param ylabel Character string for the y-axis label. Default is
#'   \code{NULL}.
#'
#' @return A \code{ggplot} object.
#'
#' @examples
#' pooled <- data.frame(
#'   variable = "v1",
#'   ymin = 1,
#'   lower = 2,
#'   middle = 3,
#'   upper = 4,
#'   ymax = 5
#' )
#' class(pooled) <- c("dsPooledBoxPlot", class(pooled))
#'
#' plot.dsPooledBoxPlot(pooled)
#' plot(pooled)
#'
#' @export
#' @importFrom ggplot2 ggplot geom_boxplot aes facet_wrap scale_fill_brewer xlab ylab
plot.dsPooledBoxPlot <- function(x, xlabel = NULL, ylabel = NULL, ...) {
  data <- x

  has_group1 <- "group" %in% names(data)
  has_group2 <- "group2" %in% names(data)

  pl <- ggplot2::ggplot(data) +
    ggplot2::geom_boxplot(stat = "identity", ggplot2::aes(x=variable, lower=lower,
                                                          upper=upper, ymin=ymin,
                                                          ymax=ymax, middle=middle,
                                                          fill = if (!has_group1) NULL else group))
  if (has_group2) pl <- pl + ggplot2::facet_wrap(~ group2)
  if (has_group1) pl <- pl + ggplot2::scale_fill_brewer(name = "Group")
  if (!is.null(xlabel)) pl <- pl + ggplot2::xlab(xlabel)
  if (!is.null(ylabel)) pl <- pl + ggplot2::ylab(ylabel)
  pl
}

